from enum import Enum


class ATMState(Enum):
    READY_FOR_TRANSACTION = "READY_FOR_TRANSACTION"
    READ_CARD_DETAILS_AND_PIN = "READ_CARD_DETAILS_AND_PIN"
    DISPENSING_CASH = "DISPENSING_CASH"
    EJECTING_CARD = "EJECTING_CARD"
    READING_CASH_WITHDRAW_DETAILS = "READING_CASH_WITHDRAW_DETAILS"