# Generated by Django 4.2.11 on 2025-07-30 16:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moviesBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'auditorium_table',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'city_table',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_poster', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movie_table',
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('seat_number', models.CharField(max_length=255)),
                ('row', models.CharField(blank=True, max_length=255, null=True)),
                ('column', models.CharField(blank=True, max_length=255, null=True)),
                ('seat_type', models.CharField(choices=[('NORMAL', 'Normal'), ('PERINEUM', 'Perineum'), ('VIP', 'Vip')], default='NORMAL', max_length=255)),
                ('auditorium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats_auditorium', to='moviesBooking.auditorium')),
            ],
            options={
                'db_table': 'seats',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_time', models.DateTimeField()),
                ('show_end_time', models.DateTimeField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorium', to='moviesBooking.auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='moviesBooking.movie')),
            ],
            options={
                'db_table': 'show_table',
            },
        ),
        migrations.CreateModel(
            name='ShowSeats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('seat_status', models.CharField(blank=True, choices=[('BLOCKED', 'Blocked'), ('LOCK', 'Lock'), ('BOOKED', 'Booked'), ('AVAILABLE', 'Available')], max_length=255, null=True)),
                ('seats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_seats_seats', to='moviesBooking.seats')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='moviesBooking.show')),
            ],
            options={
                'db_table': 'show_seats_table',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ticket_status', models.CharField(blank=True, choices=[('BOOKED', 'Booked'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], max_length=255, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_user', to='moviesBooking.show')),
                ('show_seats', models.ManyToManyField(blank=True, null=True, related_name='city_theatre', to='moviesBooking.showseats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_user', to='moviesBooking.user')),
            ],
            options={
                'db_table': 'tickets_table',
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theatre_city', to='moviesBooking.city')),
                ('theatre', models.ManyToManyField(related_name='theatre_auditorium', to='moviesBooking.auditorium')),
            ],
            options={
                'db_table': 'theatre_table',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='show',
            field=models.ManyToManyField(blank=True, null=True, related_name='auditorium_seats', to='moviesBooking.show'),
        ),
        migrations.AddField(
            model_name='city',
            name='theatre',
            field=models.ManyToManyField(blank=True, null=True, related_name='city_theatre', to='moviesBooking.theatre'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='seats',
            field=models.ManyToManyField(blank=True, null=True, related_name='auditorium_seats', to='moviesBooking.seats'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='show',
            field=models.ManyToManyField(blank=True, null=True, related_name='auditorium_show', to='moviesBooking.show'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theatre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorium_theatre', to='moviesBooking.theatre'),
        ),
    ]
