# Generated by Django 4.2.11 on 2025-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesBooking', '0002_auditorium_city_movie_seats_show_showseats_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='theatre',
        ),
        migrations.AddField(
            model_name='theatre',
            name='auditorium',
            field=models.ManyToManyField(blank=True, null=True, related_name='theatre_auditorium', to='moviesBooking.auditorium'),
        ),
    ]
