# Generated by Django 4.2.11 on 2025-07-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesBooking', '0003_remove_theatre_theatre_theatre_auditorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
